### ISSUE TITLE
[How to support] Добавить хостер бай в партнеры, заменить текст "Мы сотрудничаем" на Партнеры, убрать текст по заголовком.

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#122]
- [x] Добавить хостер бай в партнеры (лого посередине), 
- [x] заменить текст "Мы сотрудничаем" на Партнеры, 
- [x] убрать текст под заголовком и подтянуть немного выше весь контент
- [ ] заменить текст секции "Донейт" и "Стань партнером" 
- [ ] добавить ссылку на анкету в секции "Стань волонтером" 

Ссылки на макеты:
Десктоп https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1410%3A19
Мобилка https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1410%3A173

**Comment by fr0zen** [comment]
@Omeljusik просмотри пожалуйста как тебе

**Comment by Omeljusik** [comment]
@fr0zen 
1. Не хватает ссылки на сайт https://hoster.by - открывается в новой вкладке
2. Не хватает стрелочек как на макете
![image](https://user-images.githubusercontent.com/32821205/65391420-b210d000-dd71-11e9-8f2e-fc0c072613ae.png)
3. Два последних пункта из описания не хватает. Текст нужно изменить, потому что в нем ошибка в адресе teenjob.by@gmail.com  и ссылка на анкету в первой строчке Стань волонтером https://docs.google.com/forms/d/130lf1zM6lgpancdpPOBCTfyKaML5hAgE-CMtRAam6Ws/edit#responses

**Comment by fr0zen** [comment]
@Omeljusik по стрелкам думаю над тем, что они будут прокручивать, ведь у нас пока только одна карточка) Считаешь, что это целесообразно?
