### ISSUE TITLE
[Publishing] После публикации вылазит какая-то ахинея

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#132]
### Запись экрана 9.10.2019 https://monosnap.com/file/JbGXOiRNwFbu3JJgj3gjPHurlmvGFu

Повторяется невсегда и непонятно почему. После нажатия опубликавать в качестве организации (т.е. нажатия "отправить на модерации")
Я залогинена в качестве админа

И это вылезло не то объявление, которое я публиковала, а уже опубликованное.
![image](https://user-images.githubusercontent.com/32821205/65682995-d49e3400-e064-11e9-8f00-350fd5043e4b.png)

**Comment by Omeljusik** [comment]
возможно появляется с какой-то периодичностью

**Comment by Omeljusik** [comment]
@fr0zen перенаправляй, пожалуйста, после публикации в личный кабинет.  - пока так можно решить.

Ахинея вылазит до сих пор:
- под простым аккаунтом и аккаунтом модератора
- после первой публикации - ничего, начиная со следующей - вылазят значки скорее всего тех объявлений, которые уже опубликованы.
https://monosnap.com/file/odDaySv0aplbunhugFo8fjX7bq7PpE

**Comment by fr0zen** [comment]
Верстка разваливается снизу не обрезаются тэги ссылок?)

**Comment by Omeljusik** [comment]
@fr0zen последняе (на прадакшине), выглядит так
![image](https://user-images.githubusercontent.com/32821205/66138561-814d5800-e607-11e9-931a-17d3dd7b6fba.png)

**Comment by Omeljusik** [comment]
@fr0zen последний раз публиковала (вчера 03.10) - вылезло такое (см. запись экрана с мобилки) https://drive.google.com/file/d/1181IBVSSLNH4WGUdHjF76vzkPiTHCETF/view?usp=sharing

**Comment by Omeljusik** [comment]
Да, возвращает в личный кабинет.
