### ISSUE TITLE
!!! Исправить список гродов - только города - первые областные и минск, далее в алфавитном порядке.

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#136]
![image](https://user-images.githubusercontent.com/32821205/65884616-d720c680-e3a1-11e9-94ea-1db850fd4bb9.png)

список https://github.com/Omeljusik/teenjob_development/wiki/%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D1%8B,-%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D1%8B%D0%B5-%D0%B2-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B5

**Comment by Omeljusik** [comment]
@fr0zen Привет! 
У нас первый реальный запрос на изменение от пользователя. Прямо копи-пастила сообщение)

**Comment by fr0zen** [comment]
Добавить поиск, без исключения городов

**Comment by Omeljusik** [comment]
Отлично!
