### ISSUE TITLE
[Mobile] Изменить раскладку кнопок Стажировки, Волонтерство, Мероприятия на Главной в соответствии с макетом и убрать "эти кнопки" из хедера в режиме личного кабинета и создания объявления.

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#160]
1. Макет: https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1362%3A233
![image](https://user-images.githubusercontent.com/32821205/66423931-4e470200-ea15-11e9-9991-c8d1972bcdc3.png)

2.  Убрать "эти кнопки" из хедера в режиме личного кабинета и создания объявления.

- [x] https://teenjob.by/organisation
- [x] https://teenjob.by/organisation/volunteering/create
- [x] https://teenjob.by/organisation/internship/create
- [x] https://teenjob.by/organisation/events/create

![image](https://user-images.githubusercontent.com/32821205/66424130-b0076c00-ea15-11e9-92bc-b402f5dfec37.png)

**Comment by Omeljusik** [comment]
Только сами кнопки стали больше
![image](https://user-images.githubusercontent.com/32821205/66663167-db2acf00-ec52-11e9-9581-b25fecaed7b2.png)

и меню меньше, экран как будто вытянулся за счет него
![image](https://user-images.githubusercontent.com/32821205/66663033-9f900500-ec52-11e9-90af-a4a3c2f484c7.png)

## как должно быть
![image](https://user-images.githubusercontent.com/32821205/66663249-057c8c80-ec53-11e9-9256-c3bd97dff9a6.png)

**Comment by Omeljusik** [comment]
@fr0zen во объявлениях верни, пожалуйста как было - в строчку, без шахматного порядка. Так лучше.
### Вместо:
![image](https://user-images.githubusercontent.com/32821205/66664323-fb5b8d80-ec54-11e9-915d-7bde5e658bf2.png)

### Так:
![image](https://user-images.githubusercontent.com/32821205/66664453-3958b180-ec55-11e9-81e0-2b83f584a28b.png)

**Comment by fr0zen** [comment]
@Omeljusik сейчас кнопки 137px по ширине как на макете, просто макет сделан под 360px экран, тогда под 320 я просто сделаю кнопки чуть меньше, 110px
