### ISSUE TITLE
Перевести письмо сброса пароля на русский язык.

### ISSUE THREAD

**Issue by fr0zen** [Omeljusik/teenjob_development#172]
Добрый день!
Вами был сделан запрос на изменение пароля для входа в аккаунт teenjob.by

Ссылка на изменение пароля действительна в течение 60 минут.

Если вы не делали запрос на изменение пароля, просто проигнорируйте это сообщение.

С уважением,
teenjob.by

@fr0zen Привет, все переведено, возьми этот текст, пожалуйста:) я чуток поправила)

**Comment by Omeljusik** [comment]
Я понимаю, что придираюсь)) но:

С уважением,
teenjob.by

Это важно, сейчас, раз уж мы уже действуем как интернет-портал, то называемся teenjob.by

![image](https://user-images.githubusercontent.com/32821205/66704383-19dc8a00-ed24-11e9-892c-83c82797e3c5.png)

**Comment by fr0zen** [comment]
@Omeljusik все верно, это не придирки. Поправил.
