### ISSUE TITLE
Сделать favicon

### ISSUE THREAD

**Issue by fr0zen** [Omeljusik/teenjob_development#22]
Сделать значок сайта, который будет отображаться в браузере. 
- [x] Иконка для десктопа
- [x] Для андроида
- [x] Для айфона

**Comment by Omeljusik** [comment]
@fr0zen  Фафикон не отображается на внутренних страницах (страницах с объявлениями)
![image](https://user-images.githubusercontent.com/32821205/66142492-25d29880-e60e-11e9-9e94-732306515ca1.png)

**Comment by fr0zen** [comment]
@Omeljusik тут попробуй обновить странички через Ctrl+Shift+R, фавикон должен появиться.

**Comment by Omeljusik** [comment]
есть - буду тестить на продакшине
