### ISSUE TITLE
[вход] минимум 8 символов в пароле

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#3]

**Comment by Omeljusik** [comment]
@fr0zen не могу вспомнить, что здес не так. Вроде как, он подсвечивал красным, что нужно ввести минимум 8 символов, а я скорее всего поторопилась создать ишью. Если это так, то закрой, пожалуйста.

**Comment by fr0zen** [comment]
@Omeljusik сейчас мин 8 у нас
