### ISSUE TITLE
[Filtr] Добавить в профобласти вариант "Все профобласти", который при выборе не будет фильтровать по профобластям. Сейчас можно выбрать только что-то одно.

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#39]
Добавить в профобласти вариант "Все профобласти", который при выборе не будет фильтровать в принципе по профобластям. 
Сейчас можно выбрать только что-то одно. По умолчанию, высвечивается "Администрирование"
http://teenjob.by/internship
![image](https://user-images.githubusercontent.com/32821205/64321601-88158a80-cfc9-11e9-80a4-794764b6a8ec.png)

**Comment by fr0zen** [comment]
"
