### ISSUE TITLE
[Registration] Сайт ломается при попытке зарегистрироваться

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#44]
Попробовать самому: http://teenjob.by/register
Запись экрана: https://drive.google.com/file/d/1_kn6jnf3LVD_y782lB2tlOW-T26xcxOz/view?usp=sharing

**Comment by Omeljusik** [comment]
@fr0zen та же проблема все еще существует - не могу зарегистрировать организацию.

**Comment by fr0zen** [comment]
@Omeljusik попробуй еще раз, осталась ли?
