### ISSUE TITLE
Стажировки и волонтерства должны выводиться на одну страницу

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#45]
## Как есть
Волонтерство и Стажировки сейчас - это разные страницы с разным содержанием.
https://drive.google.com/file/d/1H0GJaD1gpqB5KJaOCY5Eg78xIgeXS7vi/view?usp=sharing

## Как должно быть
Волонтерство и стажировки публикуются на одной страничке (например, по адресу all-jobs), на которой их можно отсортировать с помощью фильтра.

![image](https://user-images.githubusercontent.com/32821205/64478749-90321d80-d1b5-11e9-815b-217587412918.png)

### Другие правила:
1. При выборе категории на главной странице "Стажировка" и нажатии поиск мы переходи на общую страничку, на которой отсортированы стажировки по указанному запросу (или просто все стажировки, если запрос не был введен). В фильтре стоит галочка на стажировках.
С волонтерством также.

![image](https://user-images.githubusercontent.com/32821205/64478663-09c90c00-d1b4-11e9-9d07-80ea5e75dd61.png)

2. При переходе по ссылке в меню "Стажировки", показывается общая страница с отфильтрованными объявлениями - только все стажировки. Галочка в фильтре стоит на стажировках.
С "Волонтерство" также.

![image](https://user-images.githubusercontent.com/32821205/64478663-09c90c00-d1b4-11e9-9d07-80ea5e75dd61.png)

* p.s. на последних картинках адрес all-job, но правильнее all-jobs.

**Comment by fr0zen** [comment]
@Omeljusik как смотришь на такую структуру сайта
/offers - стажировка + волонтерства
/internships
/volunteerings
/events
?
