### ISSUE TITLE
[Mobile] Поправить верстку внутренних стажировок/волонтерства

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#63]
## Как сейчас:
![image](https://user-images.githubusercontent.com/32821205/64613753-986da100-d3df-11e9-9b13-169c7e73334d.png)

## Как поправить
Основное
- без кнопки Назад
- от хедере до заголовка 50 px
- от заголовка до организации 18 px
- от пунктов до описания 24 px
- от описания до контактов 50 px
- от контактов до кнопки 70 px
- от кнопки до Опубликовано 24 px
- от пожаловаться до футера 76 px

### Ссылка на макет 
https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=592%3A109

**Comment by Omeljusik** [comment]
@fr0zen на мобильной версии все отлично, спасибо.
На десктопе - внеси, пожалуйста, такие изменения 
![image](https://user-images.githubusercontent.com/32821205/66596691-060b1980-eba6-11e9-8ca9-71717b94486b.png)

чуть все же опустить "назад" и поднять весь текст и собственно название организации к названию объявления, так, чтобы расстояние между названиями было вместо 32 - 24 px.
макет https://www.figma.com/file/OD9PcqDHdfLJHDLJi34l3wAH/teenjob?node-id=1628%3A4

**Comment by fr0zen** [comment]
@Omeljusik исправлено и на мероприятиях

**Comment by Omeljusik** [comment]
@fr0zen подтяни, пожалуйста, кнопку выше
![image](https://user-images.githubusercontent.com/32821205/66664767-d7e51280-ec55-11e9-930e-0b37a92f78f3.png)

**Comment by Omeljusik** [comment]
Да, все отлично, спасибо - можно лить на продакшн!
