### ISSUE TITLE
[Admin_Org] Заменить текст кнопки Опубликовать на "Отправить на модерацию", сделать кнопку чуть длиннее, расположить по середине рабочей области

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#72]
## Что изменить
![image](https://user-images.githubusercontent.com/32821205/64710142-13a68400-d4c0-11e9-9d10-cbe69729fd0e.png)

### Параметры кнопки 304 на 50, располагается по середине рабосай области. Сейчас немного сдвинута вправо:
![image](https://user-images.githubusercontent.com/32821205/64710920-79474000-d4c1-11e9-94ec-a1537a129aa6.png)

**Comment by Omeljusik** [comment]
@fr0zen Работает только в Мероприятиях.
В стажировках и волонтерстве до сих пор "Опубликовать", надо "Отправить на модерацию"

**Comment by Omeljusik** [comment]
@fr0zen Все еще также и по надписи и по расположению кнопки (смотрела на продашине)
![image](https://user-images.githubusercontent.com/32821205/66424703-cfeb5f80-ea16-11e9-84c7-7fc09d8c88a7.png)

В стажировках
![image](https://user-images.githubusercontent.com/32821205/66424740-e85b7a00-ea16-11e9-8ea0-d494eddf2bf6.png)

В волонтерстве и мероприятиях слова правильные

**Comment by fr0zen** [comment]
@Omeljusik это пока только на dev.

**Comment by Omeljusik** [comment]
Ок, можно на прадакшн.
