### ISSUE TITLE
! [Admin_Org] Cделать автоматическую ужимку размера preview для мероприятий при загрузке

### ISSUE THREAD

**Issue by Omeljusik** [Omeljusik/teenjob_development#94]
### Перепробовала много разных вариантов, так и не подобрала. Нужно прописать в этом уведомлении какого размера должна быть картинка от до по ширине и длине.

Сейчас картинка должна быть не меньше 256 Kb

https://teenjob.by/organisation/events/create

![image](https://user-images.githubusercontent.com/32821205/64952822-fee43a80-d889-11e9-9fe1-e39fba3f4ee1.png)

**Comment by fr0zen** [comment]
png load

**Comment by Omeljusik** [comment]
Хорошо, буду смотреть.

**Comment by Omeljusik** [comment]
У меня не получается загрузить картинку 3.1 mb, 4159 x 2762

@fr0zen напиши, пожалуйста, под какие параметры подстраивается изображение и какие максимальные допустимые значения для загрузки в мб и пикселях.

**Comment by Omeljusik** [comment]
у меня получилось загрузить по мб - максимум 2,32, но специально больше картинки не подгоняла, около 3-х и три мб уже точно не грузилось. Это я для себя. @fr0zen напиши, какие параметры ты задавал.

**Comment by Omeljusik** [comment]
@fr0zen Напиши, пожалуйста, сразу в вики https://github.com/Omeljusik/teenjob_development/wiki/%D0%9A%D0%B0%D0%BA-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%BC
